
#server.port=8084
#
#dh.keycloak.serverUrl=http://localhost:8080
#dh.keycloak.realm = digital-house
#dh.keycloak.clientId = interno
#dh.keycloak.clientSecret = hfIIlnFD2MUPQOFA8k7jKW4XEALEkLJs

server:
    port: 8084



dh:
    keycloak:
        auth-server-url: http://localhost:8080
    master:
        realm: master
        username: admin
        password: admin
        clientId: admin-cli
    nuevoReino:
        realm: cytelsystem
        new_username: intadmin
        new_password: password
        new_realm_roles: USER
