
server:
    port: 8084

dh:
    keycloak:
        auth-server-url: http://localhost:8080
    master:
        realm: master
        username: admin
        password: admin
        clientId: admin-cli
    nuevoReino:
        realm: cytelsystem
        new_username: intadmin
        new_password: password
        new_realm_roles: USER
