server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/dh
        registration:
          api-gateway-service:
            provider: keycloak-provider
            client-id: api-gateway-client
            client-secret: vj4VpqGp8CKru6rRORf6DANrF3FFVX1C
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak

spring.cloud.gateway:
  default-filters:
    - TokenRelay
  routes:
    - id: hello-service
      uri: http://localhost:8086
      predicates:
        - Path=/hello/**
