server:
  port: 8084

dh:
  keycloak:
    auth-server-url: http://localhost:8080
  master:
    realm: master
    username: admin
    password: admin
    clientId: admin-cli
  nuevoReino:
    realm: mercadopagohjm
    new_realm_roles: USER
    new_username1: intadmin
    new_password1: password
    new_clientScopeName: gruposhj